[main]
# Postgres prompt
# \t - Current date and time
# \u - Username
# \h - Short hostname of the server (up to first '.')
# \H - Hostname of the server
# \d - Database name
# \p - Database port
# \n - Newline
prompt = "\\u@\\h:\\d> "


# history
history_file = "default"

# log
log_file = "default"

# style
# Available:
#   monokai
#   dracula
#   github-dark
#   gruvbox
#   nord
#   onedark
#   solarized-dark
#   solarized-light
#   tokyonight-night
#   catppuccin-mocha
style = "monokai"
